
spring:
  application:
    name: dubbo-consumer-sample

demo:
  service:
    version: 1.0.0

dubbo:
  registry:
    address: nacos://127.0.0.1:8848 #zookeeper://127.0.0.1:2181

server:
  port: 8080
  servlet:
    context-path: /consumer